platform :ios, '10.0'
use_frameworks!

def used_pods
	pod 'AFNetworking', '~> 2.0'
	pod 'JTCalendar', '~> 2.0'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SCLAlertView-Objective-C'
	pod 'youtube-ios-player-helper', '~> 0.1.4'
	pod 'TOCropViewController'
	pod 'CTPanoramaView', '~> 1.1'
	pod 'GCDWebServer', '~> 3.0'
	pod 'JPSVolumeButtonHandler'
	pod 'SSZipArchive'
	pod 'LMGraphView'

	pod 'Firebase/Messaging'
	pod 'Firebase/Core'
	pod 'Firebase/MLVision'
	pod 'Firebase/MLVisionTextModel'
end
 
target 'LAB360-Dev' do
    used_pods
end
 
target 'LAB360-Prod' do
    used_pods
end

target 'LAB360-ProdS3' do
    used_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
