# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneInternational-Dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneInternational-Dev

	pod 'AFNetworking', '~> 2.0'
	pod 'JTCalendar', '~> 2.0'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SCLAlertView-Objective-C'
	pod 'youtube-ios-player-helper', '~> 0.1.4'
	pod 'TOCropViewController'
	pod 'CTPanoramaView', '~> 1.1'
	pod 'GCDWebServer', '~> 3.0'
	pod 'JPSVolumeButtonHandler'
	pod 'SSZipArchive'
	pod 'LMGraphView'
	pod 'Firebase/Messaging'
	pod 'Firebase/Core'
	pod 'Firebase/MLVision'
	pod 'Firebase/MLVisionTextModel'

end

target 'OneInternational-Prod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneInternational-Prod
	pod 'AFNetworking', '~> 2.0'
	pod 'JTCalendar', '~> 2.0'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SCLAlertView-Objective-C'
	pod 'youtube-ios-player-helper', '~> 0.1.4'
	pod 'TOCropViewController'
	pod 'CTPanoramaView', '~> 1.1'
	pod 'GCDWebServer', '~> 3.0'
	pod 'JPSVolumeButtonHandler'
	pod 'SSZipArchive'
	pod 'LMGraphView'
	pod 'Firebase/Messaging'
	pod 'Firebase/Core'
	pod 'Firebase/MLVision'
	pod 'Firebase/MLVisionTextModel'


end
